### PR TITLE
Update to 0.10.4

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
needs gcc 4.9

**Comment by jschueller** [comment]
https://github.com/conda-forge/conda-forge.github.io/issues/29

**Comment by jschueller** [comment]
Hi @conda-forge/core I would need gcc>=4.9, what do I do ?

**Comment by msarahan** [comment]
I'm not sure we have an answer right now.  Continuum (@mingwandroid and I) are working on new gcc compiler packages (6.3.0).  We don't have an exact ETA, but it should be within a few weeks.

**Comment by jschueller** [comment]
ok, great news!

**Pull request closed without merging**
