### PR TITLE
Update to v1.5.0

### PR DESCRIPTION
**Pull request by Aspard**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Aspard** [comment]
@conda-forge-admin, please rerender

**Comment by Aspard** [comment]
Hi @jschueller,

It seems that the new release of pyAgrum introduces a lot of issues for conda wheels. If linux jobs seem unable to find `Python_INCLUDE_DIRS` (but only for python <3.10 ?), some osx jobs ends during installing or building phases (but once again, the behavior is not the same depending on the python used).

Do you think the changes introduced with our new use of cmake could be the cause of all these issues ?

**Comment by jschueller** [comment]
it looks some other python version are interfering because the test part only look for the interpreter first,
maybe try to pass `Python_EXECUTABLE=${PYTHON}`

**Comment by jschueller** [comment]
if that doesnt work pass instead:
```
-DPython_FIND_STRATEGY=LOCATION \
  -DPython_ROOT_DIR=${PREFIX} \
```

**Comment by Aspard** [comment]
> 

I'll try that !

**Comment by Aspard** [comment]
Ah, it was almost perfect!

**Comment by jschueller** [comment]
apparently it needs the include dir too:
`-DPython_INCLUDE_DIR=${PREFIX}/include/python${PY_VER}`

**Comment by Aspard** [comment]
It worked, thanks again for your precious help!

**Pull request merged**
