### PR TITLE
Python 3.6

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
I've got a package conflict error with python3.6 when testing, maybe someone from @conda-forge/core 
could tell me what's up:
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - pyagrum 0.10.3 py36_1
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by jjhelmus** [comment]
> I've got a package conflict error with python3.6 when testing

It does not look a Python 3.6 package for [pydotplus](https://github.com/conda-forge/pydotplus-feedstock) is [available yet for Linux](https://anaconda.org/conda-forge/pydotplus/files).  Not sure why this is true since an OS X py36 package is available.  Opened issue conda-forge/pydotplus-feedstock#5 and submitted conda-forge/pydotplus-feedstock#6 to attempt to fix the issue.

**Comment by jschueller** [comment]
Thanks, the error message is not explicit at all.

**Comment by jjhelmus** [comment]
I agree that the message is not very verbose.  You could try filing an issue (or seeing if one already exists) with [conda](https://github.com/conda/conda).

**Comment by jschueller** [comment]
I did not find such an issue. The tracker of conda is scary: 1250+ opened issued!

**Pull request merged**
