### PR TITLE
Build on osx/win

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
@jakirkham i've got an error with isl when cmake is checking for the compiler (gcc in this recipe):
dyld: Library not loaded: @rpath/libisl.10.dylib
https://travis-ci.org/conda-forge/pyagrum-feedstock/jobs/167379108

maybe gcc from defaults wants libisl.10.dylib but isl from conda-forge provides libisl.15.dylib

**Comment by jakirkham** [comment]
Really, I thought Continuum fixed the pinning? @mcg1969 any idea why we are now getting the wrong `isl` again? 😕

**Comment by mcg1969** [comment]
No, you're going to need to reach out to @kalefranz. I'm not a day-to-day maintainer of conda these days.

**Comment by jakirkham** [comment]
Ok thanks.

**Pull request merged**
