### PR TITLE
Update to v1.16.0

### PR DESCRIPTION
**Pull request by Aspard**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Aspard** [comment]
@conda-forge-admin, please rerender

**Comment by Aspard** [comment]
@conda-forge-admin, please rerender

**Comment by Aspard** [comment]
Hey @jschueller,

We are having an intriguing situation over here and you might be able to help us.

Some tests are not working on osx/64bits for no obvious reason; they were working before re-rendering the project but not anymore.

Do you know, by any chance, what could explain this ? Is there a new mechanism for mac that we are not aware of?

I also just noticed that tests were not visible on the logs of osx/arm, are they just hidden or is there something to add to the recipe for them to be completed ?

Thanks in advance,

Gaspard

**Comment by jschueller** [comment]
hello,
it might be the new clang, I'll try something

**Comment by jschueller** [comment]
hello,
its an issue with clang>=17
https://github.com/llvm/llvm-project/issues/71196
a workaround is to pass -fno-assume-unique-vtables, see #177

**Comment by Aspard** [comment]
Thanks for your help @jschueller!

**Pull request merged**
