### PR TITLE
0.13.6

### PR DESCRIPTION
**Pull request by LTorti**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by LTorti** [comment]
@jschueller : I am a bit confused why the windows compilation are failing... Is there a way to force the binary generation for https://github.com/openturns/build-agrum/releases/download/v0.13.6/agrum-0.13.6-py2.7-x86_64.zip ?

**Comment by jschueller** [comment]
Sorry I dont think there's another way, as agrum/openturns have to be built with the same toolchain, but the conda-forge mingw toolchain is incompatible with the openturns one afaik.

The Linux fails because of dropped mesa packages, you will want to add
 ```/usr/bin/sudo -n yum install -y mesa-libGL-devel mesa-libGLU-devel libX11-devel libXt-devel libXrender-devel libXext-devel libXdmcp-devel```
in circleci/build_steps.sh after "source run_conda_forge_build_setup", and add a file recipe/yum_requirements.txt:
```
# TODO get rid of this and use xorg package.
mesa-libGL-devel
mesa-libGLU-devel
libX11-devel
libXt-devel
libXrender-devel
libXext-devel
libXdmcp-devel
```

The osx build fails because of an undefined symbol.

**Comment by jschueller** [comment]
Also, the macos build passes on the bot PR update, as the renrendering updated the xcode/clang combination, so rerendering here should fix the mac build too.

**Comment by jschueller** [comment]
What are the last 2 commits about ? The Linux builds were already passing.

**Comment by LTorti** [comment]
> 
> 
> Also, the macos build passes on the bot PR update, as the renrendering updated the xcode/clang combination, so rerendering here should fix the mac build too.

I'v already relaunched the builds using travis and it's still not working (I relaunch it just now to retry).

To rerender should I use `_at_conda-forge-admin, please rerender` ?

**Comment by LTorti** [comment]
> 
> 
> What are the last 2 commits about ? The Linux builds were already passing.

The linux builds for python 2.7 still had issues with matplotlib so I added two commands to update pip and install matplotlib. It fixed the issue but I am not sure this is the proper procedure given that we are building conda packages.

**Comment by LTorti** [comment]
> 
> 
> Sorry I dont think there's another way, as agrum/openturns have to be built with the same toolchain, but the conda-forge mingw toolchain is incompatible with the openturns 

Does this means we won't have Windows packages ?

**Comment by jschueller** [comment]
Not at all, I can publish the 0.13.6 version.

**Comment by jschueller** [comment]
I triggered the windows build but there's a bug in agrum, see agrum's bugtracker.

**Pull request closed without merging**
